os:
  - linux
  - osx

osx_image: xcode10.1

sudo: required

dist: xenial

language: cpp

addons:
  apt:
    sources:
    - xenial
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu xenial main'
    packages:
    - gcc
    - g++
    - libjsoncpp-dev
    - uuid-dev
    - zlib1g-dev
    - postgresql-server-dev-10
    - openssl
    - libssl-dev
    - libsqlite3-dev
    - build-essential
    - cmake
  homebrew:
    packages:
    - jsoncpp
    - ossp-uuid
    - openssl
    - cmake
    - libtool
    - lz4
    - postgresql
    - mariadb
    - sqlite3
    update: true

script:
  - ./build.sh && ./test.sh
